name: Blog in Readme

on:
  push:
    branches:
      - master
  schedule:
    # Runs every day at 3pm UTC (11pm SG)
    - cron: "0 15 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: https://www.eydev.club/en.rss.xml
          committer_email: enriqueyerren@gmail.com
          committer_username: eydev
